// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQsK1ZB7SGpS1QpnTiZnSt-AUmh327TqE',
    appId: '1:645882986447:web:4632399224ace9f00e1cba',
    messagingSenderId: '645882986447',
    projectId: 'praticas3-91ab1',
    authDomain: 'praticas3-91ab1.firebaseapp.com',
    storageBucket: 'praticas3-91ab1.firebasestorage.app',
    measurementId: 'G-NPKF0XZRMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDry65KXWGjfAPwazJawULR6sXDlr8otpk',
    appId: '1:645882986447:android:c45aad04cd28dd510e1cba',
    messagingSenderId: '645882986447',
    projectId: 'praticas3-91ab1',
    storageBucket: 'praticas3-91ab1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAedvqrNGxvmi-XZtJuS5LkQZYiqnRE4wc',
    appId: '1:645882986447:ios:5305cb565c402af90e1cba',
    messagingSenderId: '645882986447',
    projectId: 'praticas3-91ab1',
    storageBucket: 'praticas3-91ab1.firebasestorage.app',
    iosBundleId: 'com.example.xuka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAedvqrNGxvmi-XZtJuS5LkQZYiqnRE4wc',
    appId: '1:645882986447:ios:5305cb565c402af90e1cba',
    messagingSenderId: '645882986447',
    projectId: 'praticas3-91ab1',
    storageBucket: 'praticas3-91ab1.firebasestorage.app',
    iosBundleId: 'com.example.xuka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQsK1ZB7SGpS1QpnTiZnSt-AUmh327TqE',
    appId: '1:645882986447:web:74ef7dec6d3e4b9a0e1cba',
    messagingSenderId: '645882986447',
    projectId: 'praticas3-91ab1',
    authDomain: 'praticas3-91ab1.firebaseapp.com',
    storageBucket: 'praticas3-91ab1.firebasestorage.app',
    measurementId: 'G-VYHV4TP4W2',
  );

}